### ISSUE TITLE
Location in init.py is not the developer's location, rather where the add-on changes UI

### ISSUE THREAD

**Issue by z-aki** [thebadking/animationrender#1]
https://wiki.blender.org/wiki/Process/Addons/Guidelines/metainfo

> location
> 
> (string)
> Explains where the new functionality can be found. For example: "View3D > Properties > Measure"
> 

https://github.com/thebadking/animationrender/blob/master/animationrender/__init__.py#L25

**Comment by thebadking** [comment]
thank you, first addon, corrected
