### ISSUE TITLE
file names missing left-padded 0s (v1, blender 2.9)

### ISSUE THREAD

**Issue by jakedowns** [thebadking/animationrender#2]
Hello there, thanks for this utility, i'm interesting in trying it out as blender keeps crashing on me. I'm testing v1 with 2.9

one thing i'm noticing right off the bat is that the file-numbering is different. 

i have a project that has rendered ~900 out of 1000 frames.

my first file is numbered 0001.png

this add-on's first output files were 1.png, 2.png with no padded 0's

**Comment by thebadking** [comment]
I didnt see the need for the padding as the imported pngs get organized properly on the video editor.
is the addon solving your crashing problems?
added padding to the menu, just select the total digits you need in your case 4.
https://github.com/thebadking/animationrender/releases/tag/1.1

**Comment by jakedowns** [comment]
no it's ok, don't _need_ the padded zeros, just wanted to point out that it won't play nice with un-checking "overwrite" in the normal blender render settings, and will probably lead to duplicated frames so that's something for people to consider when using the plugin :)

**Comment by thebadking** [comment]
did it work?

**Comment by jakedowns** [comment]
oh haha, yes thank you very much!
